plugins {
    // see https://projects.neoforged.net/neoforged/moddevgradle for new versions
    id 'net.neoforged.moddev' version '2.0.134' apply false
}

subprojects {
    tasks.withType(JavaCompile).configureEach {
        options.compilerArgs += ['-Xdoclint:none']
    }
    tasks.withType(Javadoc).configureEach {
        options.addStringOption('Xdoclint:none', '-quiet')
    }
}
