#!/usr/bin/env python3
"""Generates placeholder (template) model/texture assets for Multi Item Frame.

These are NOT final art - they are simple, clearly-labeled stand-ins so the
mod is playable/inspectable in-game before a real artist does the pixel art
pass (see TASKS.md ch.4). Regenerate by deleting the affected files and
re-running this script; it will not overwrite files that already look like
hand-authored art (it always overwrites, so re-run only when you actually
want fresh placeholders). Language files (`en_us.json`) live per-loader
(`forge`/`neoforge`), not here, and are not regenerated by this script.

Conventions baked into these placeholders (documented in TASKS.md ch.4 notes):
- Highlight rendering (`HighlightMode.FRAME` / `FILL`) is done by tinting a
  plain white overlay texture per-vertex to the slot's chosen DyeColor at
  render time, not by baking 16 pre-colored texture variants. Hence only two
  highlight textures exist: `highlight_frame.png` (outline) and
  `highlight_fill.png` (solid).
- The background is a separate texture (`background.png`) so
  `isBackgroundVisible()` can skip drawing it independently of the frame
  border/highlight layers.
- Item icons are flat 2D icons (`item/generated`), not 3D `builtin/entity`
  models like vanilla Item Frame - simpler, and the frame's actual displayed
  item is already visible in-world without needing a held/GUI 3D preview.

Run: python tools/generate_placeholder_assets.py
"""
import json
import os

from PIL import Image, ImageDraw

MOD_ID = "multiitemframe"
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSETS = os.path.join(ROOT, "common", "src", "main", "resources", "assets", MOD_ID)

# Mirrors common/src/main/java/wtf/vd/multiitemframe/frame/FrameSize.java
FRAME_SIZES = {
    "1x1": (1, 1, [(0, 0)]),
    "1x2": (1, 2, [(0, 0), (0, 1)]),
    "2x1": (2, 1, [(0, 0), (1, 0)]),
    "1and2": (2, 2, [(0, 0), (0, 1), (1, 1)]),
    "2and1": (2, 2, [(0, 0), (1, 0), (0, 1)]),
    "2x2": (2, 2, [(0, 0), (1, 0), (0, 1), (1, 1)]),
}

GRAY = (198, 198, 198, 255)
DARK_GRAY = (150, 150, 150, 255)
BORDER = (30, 30, 30, 255)
GLOW_BORDER = (255, 214, 92, 255)


def save(image, *path_parts):
    path = os.path.join(ASSETS, *path_parts)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    image.save(path)


def frame_icon(columns, rows, slots, size=16, border_color=BORDER):
    """A flat placeholder icon: bordered square with darker cells marking each slot's position."""
    img = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)
    draw.rectangle([0, 0, size - 1, size - 1], fill=GRAY, outline=border_color)
    cell_w = (size - 4) / columns
    cell_h = (size - 4) / rows
    for (cx, cy) in slots:
        x0 = round(2 + cx * cell_w)
        y0 = round(2 + cy * cell_h)
        x1 = round(2 + (cx + 1) * cell_w) - 1
        y1 = round(2 + (cy + 1) * cell_h) - 1
        draw.rectangle([x0, y0, x1, y1], fill=DARK_GRAY, outline=border_color)
    return img


def write_json(data, *path_parts):
    path = os.path.join(ASSETS, *path_parts)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write("\n")


def item_model(texture_path):
    return {"parent": "minecraft:item/generated", "textures": {"layer0": texture_path}}


def main():
    for size_id, (columns, rows, slots) in FRAME_SIZES.items():
        # Non-glowing item icon + model.
        icon = frame_icon(columns, rows, slots)
        save(icon, "textures", "item", f"frame_{size_id}.png")
        write_json(item_model(f"{MOD_ID}:item/frame_{size_id}"), "models", "item", f"frame_{size_id}.json")

        # Glowing item icon (accented border) + model.
        glow_icon = frame_icon(columns, rows, slots, border_color=GLOW_BORDER)
        save(glow_icon, "textures", "item", f"glow_frame_{size_id}.png")
        write_json(item_model(f"{MOD_ID}:item/glow_frame_{size_id}"), "models", "item", f"glow_frame_{size_id}.json")

    # In-world entity textures: a single stretched border texture per glow state (see
    # MultiItemFrameRenderer, ch.4 TODO) rather than one per FrameSize/slot-count.
    save(frame_icon(1, 1, [], size=32), "textures", "entity", "frame.png")
    save(frame_icon(1, 1, [], size=32, border_color=GLOW_BORDER), "textures", "entity", "frame_glow.png")

    # Background layer, shown/hidden independently via isBackgroundVisible().
    background = Image.new("RGBA", (16, 16), DARK_GRAY)
    ImageDraw.Draw(background).rectangle([0, 0, 15, 15], outline=BORDER)
    save(background, "textures", "entity", "background.png")

    # Highlight overlays: plain white so the renderer can tint them to any DyeColor per slot.
    highlight_frame = Image.new("RGBA", (16, 16), (0, 0, 0, 0))
    draw = ImageDraw.Draw(highlight_frame)
    draw.rectangle([0, 0, 15, 15], outline=(255, 255, 255, 255), width=2)
    save(highlight_frame, "textures", "entity", "highlight_frame.png")

    highlight_fill = Image.new("RGBA", (16, 16), (255, 255, 255, 255))
    save(highlight_fill, "textures", "entity", "highlight_fill.png")


if __name__ == "__main__":
    main()
